apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: presenton-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
spec:
  rules:
  - host: presenton.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: presenton-service
            port:
              number: 80
