apiVersion: v1
kind: Service
metadata:
  name: presenton-service
  namespace: presenton
  labels:
    app: presenton
    app.kubernetes.io/name: presenton
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: presenton
    app.kubernetes.io/name: presenton
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: presenton-api-service
  namespace: presenton
  labels:
    app: presenton
    app.kubernetes.io/name: presenton
    app.kubernetes.io/component: api
spec:
  selector:
    app: presenton
    app.kubernetes.io/name: presenton
    app.kubernetes.io/component: frontend
  ports:
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
